
[functions.war-watcher]
enabled = true
verify_jwt = true
import_map = "./functions/war-watcher/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/war-watcher/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/war-watcher/*.html" ]

[functions.status-watcher]
enabled = true
verify_jwt = true
import_map = "./functions/status-watcher/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/status-watcher/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/status-watcher/*.html" ]

[functions.daily-networth]
enabled = true
verify_jwt = true
import_map = "./functions/daily-networth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/daily-networth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/daily-networth/*.html" ]

[functions.sync-items]
enabled = true
verify_jwt = true
import_map = "./functions/sync-items/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-items/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-items/*.html" ]

[functions.sync-bazaar-prices]
enabled = true
verify_jwt = true
import_map = "./functions/sync-bazaar-prices/deno.json"
entrypoint = "./functions/sync-bazaar-prices/index.ts"

[functions.check-stock-alerts]
enabled = true
verify_jwt = true
import_map = "./functions/check-stock-alerts/deno.json"
entrypoint = "./functions/check-stock-alerts/index.ts"

[functions.update-chain-targets]
enabled = true
verify_jwt = true
import_map = "./functions/update-chain-targets/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-chain-targets/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-chain-targets/*.html" ]

[functions.sync-chain-targets]
enabled = true
verify_jwt = true
import_map = "./functions/sync-chain-targets/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-chain-targets/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-chain-targets/*.html" ]

[functions.sync-user-stats]
enabled = true
verify_jwt = true
import_map = "./functions/sync-user-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-user-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-user-stats/*.html" ]

[functions.sync-bank-history]
enabled = true
verify_jwt = true
import_map = "./functions/sync-bank-history/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-bank-history/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-bank-history/*.html" ]

[functions.update-stocks]
enabled = true
verify_jwt = true
import_map = "./functions/update-stocks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-stocks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-stocks/*.html" ]
